### ISSUE TITLE
Large amount of repeated code

### ISSUE THREAD

**Issue by janash** [KIT-MBS/pyrexMD#1]
In `gmx.py` there is a very large amount of repeated code.

For example, the code 

```
# clean up
    odir = _misc.dirpath(_misc.realpath(o))
    clean_up("./", verbose=False)
    clean_up(odir, verbose=False)

    # save message
    o_file = _misc.realpath(o)
    _misc.cprint(f"Saved file as: {o_file}", cfg.cprint_color)

    if log:
        logdir = _misc.mkdir(f"{odir}/logs")
        logfile = f"{logdir}/grompp.log"
        if not log_overwrite:
            log_names = [f"{logdir}/grompp_{i}.log" for i in range(1, 1000)]
            for name in log_names:
                if name in glob.glob(f"{logdir}/*.log"):
                    continue  # skip existing log_name
                else:
                    logfile = name
                    break  # stop at first new log_name
        with open(logfile, "w") as fout:
            _misc.cprint(f"Saved log as: {logfile}", cfg.cprint_color)
            fout.write(f"STDERR:\n\n{stderr}\n")
            fout.write(f"STDOUT:\n\n{stdout}\n")
            clean_up(logdir, verbose=False)
    return o_file
```

or some *very slight* variation is repeated several times. This always occurs after a Gromacs function is called. Before the gromacs functions are called, output file names etc are set. This occurs in every function which wraps Gromacs functions.

Examples:
- [1](https://github.com/KIT-MBS/pyrexMD/blob/78bcec7104c1c591ee4671457c08bb4d690e02ee/pyrexMD/gmx.py#L229)
- [2](https://github.com/KIT-MBS/pyrexMD/blob/78bcec7104c1c591ee4671457c08bb4d690e02ee/pyrexMD/gmx.py#L318)
- [3](https://github.com/KIT-MBS/pyrexMD/blob/78bcec7104c1c591ee4671457c08bb4d690e02ee/pyrexMD/gmx.py#L403)
- [4](https://github.com/KIT-MBS/pyrexMD/blob/78bcec7104c1c591ee4671457c08bb4d690e02ee/pyrexMD/gmx.py#L542)
- [5](https://github.com/KIT-MBS/pyrexMD/blob/78bcec7104c1c591ee4671457c08bb4d690e02ee/pyrexMD/gmx.py#L619)

Some of this (such as cleaning the directory) could be moved into `misc.HiddenPrints(verbose=verbose)`, though I imagine then it would be appropriate to change the name. Alternatively I would suggest writing a decorator for these Gromacs functions which sets up the configuration and output before calling the function and logs appropriate data and cleans up after the function is called. If you are not able to write a decorator, I advise at the very least moving this similar code into a function that is called.

**Comment by janash** [comment]
Additionally, there are two functions which seem to be exactly the same, `editconf` and `convert_TPR2PDB`: https://github.com/KIT-MBS/pyrexMD/blob/78bcec7104c1c591ee4671457c08bb4d690e02ee/pyrexMD/gmx.py#L258

One of these should be eliminated, or they should be aliased, ie

```
convert_TPR2PDB = editconf
```

To ensure that they are always the same if they are meant to be the same function.

**Comment by ArtVoro** [comment]
i adressed this issue with call of help functions now. thanks
